// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace UrlShortener.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.UrlManagement", b =>
                {
                    b.Property<string>("ShortUrl")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShortUrl");

                    b.ToTable("url_management");

                    b.HasData(
                        new
                        {
                            ShortUrl = "HtyU83f",
                            OriginalUrl = "https://code-maze.com/ultimate-aspnetcore-webapi-second-edition/?source=nav"
                        },
                        new
                        {
                            ShortUrl = "YtyB45f",
                            OriginalUrl = "https://stackoverflow.com/questions/tagged/c%23"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
